#browser options: CHROME, FIREFOX, IE, EDGE
#testdata options: test1, test2, test3

testedBrowser: CHROME
testedDataSet: test1

testData:
  test1:
    envName: test1
    appUrl: http://146.59.32.4/
    timeout: 3
    iterations: 1
    customTxt: hasta la vista baby
    droppedPricesCatName: On sale
    basketIterations: 3
    testItemQuantity: 5

  test2:
    envName: test2
    appUrl: https://seleniumui.moderntester.pl/form.php
    timeout: 3
    iterations: 3
    customTxt: hasta la vista baby
    droppedPricesCatName: On sale
    basketIterations: 5
    testItemQuantity: 5



  test3:
    envName: test3
    appUrl: https://seleniumui.moderntester.pl/form.php
    timeout: 5
    iterations: 3
    customTxt: hasta la vista baby
    droppedPricesCatName: On sale
    basketIterations: 5
    testItemQuantity: 5



---